export const products = [
  {
    id: 1,
    name: "Running Shoes",
    category: "Sports",
    price: 124.9,
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images__2_-removebg-preview.png",
  },
  {
    id: 2,
    name: "Casual Sneakers",
    category: "Casual",
    price: 145.5,
    sizes: ["S", "M", "L"],
    imageUrl: "/images__3_-removebg-preview.png",
  },
  {
    id: 3,
    name: "Formal Leather Shoes",
    category: "Office Wear",
    price: 175.0,
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images__5_-removebg-preview.png",
  },
  {
    id: 4,
    name: "High-Top Sneakers",
    category: "Streetwear",
    price: 125.5,
    sizes: ["M", "L", "XL"],
    imageUrl: "/images__4_-removebg-preview.png",
  },
  {
    id: 5,
    name: "Luxury Loafers",
    category: "Evening Wear",
    price: 175.0,
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images__6_-removebg-preview.png",
  },
  {
    id: 6,
    name: "Slip-On Canvas Shoes",
    category: "Casual",
    price: 125.5,
    sizes: ["M", "L", "XL"],
    imageUrl: "/images__3_-removebg-preview.png",
  },
];
